---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: ghost
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: ghost
  chart:
    git: ssh://git@github.com/gyoza/flux-get-started
    ref: master
    path: charts/ghost
  values:
    image:
      repository: bitnami/ghost
      tag: 3.1.1-debian-9-r15
    persistence:
      enabled: false
    resources:
      requests:
        memory: 32Mi
        cpu: 10m
    service:
      type: NodePort
      port: 80
      nodePorts.http: 80
    mariadb:
      master:
        persistence:
          enabled: false
